server:
  port: 1021


spring:
  application.name: CONFIG-SERVER
  # git管理配置
  cloud.config:
    server.git:
      uri: https://github.com/bojiangzhou/lyyzoo-cloud.git
      searchPaths: /config
      username: bojiangzhou
      password: 90313lz7108

# 配置服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


  #设置本地存储配置的方式 Config Server会默认从应用的src/main/resource目录下检索配置文件。
#  profiles.active: true
  #也可以通过下面的属性来指定配置文件的位置
#  cloud.config.server.native.searchLocations: file:F:/properties/
#  虽然Spring Cloud Config提供了这样的功能，但是为了支持更好的管理内容和版本控制的功能，还是推荐使用git的方式。

#
#URL与配置文件的映射关系如下：
#
#   /{application}/{profile}[/{label}]
#   /{application}-{profile}.yml
#   /{label}/{application}-{profile}.yml
#   /{application}-{profile}.properties
#   /{label}/{application}-{profile}.properties



