
server:
    port: 1002

spring:
    application.name: eureka-server

eureka:
    instance:
        hostname: server2
#        namespace: eureka-server
#        appname: eureka-server
#        instance-id: eureka-server

    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone : http://server1:8761/eureka/,http://server3:1003/eureka/

